// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWEAoJcyVFDZnoR-x-8WV8WQluKvX5beo',
    appId: '1:157513404210:web:cc96366d2c78ca8597d12b',
    messagingSenderId: '157513404210',
    projectId: 'buraco-75af1',
    authDomain: 'buraco-75af1.firebaseapp.com',
    storageBucket: 'buraco-75af1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7yhVgOF2kb9i_w7Rl_10Zh3lQuXsfupM',
    appId: '1:157513404210:android:3916211f396f969097d12b',
    messagingSenderId: '157513404210',
    projectId: 'buraco-75af1',
    storageBucket: 'buraco-75af1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fyD6BLCW0ZmV8gny3W44C3evmDp9oMw',
    appId: '1:157513404210:ios:e886ed99a65c4b0897d12b',
    messagingSenderId: '157513404210',
    projectId: 'buraco-75af1',
    storageBucket: 'buraco-75af1.firebasestorage.app',
    iosBundleId: 'com.example.buraco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fyD6BLCW0ZmV8gny3W44C3evmDp9oMw',
    appId: '1:157513404210:ios:e886ed99a65c4b0897d12b',
    messagingSenderId: '157513404210',
    projectId: 'buraco-75af1',
    storageBucket: 'buraco-75af1.firebasestorage.app',
    iosBundleId: 'com.example.buraco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWEAoJcyVFDZnoR-x-8WV8WQluKvX5beo',
    appId: '1:157513404210:web:d2241b7a22988d9797d12b',
    messagingSenderId: '157513404210',
    projectId: 'buraco-75af1',
    authDomain: 'buraco-75af1.firebaseapp.com',
    storageBucket: 'buraco-75af1.firebasestorage.app',
  );
}
